### PR TITLE
Pull from jonasnick/secp256k1 branch schnorrsig 

### PR DESCRIPTION
**Pull request by ChristopherA**
From commit 372c4555cac1d2cba747ea691006876818c6adef

### CODE REVIEW

**Comment by ChristopherA** [comment]
@jonasnick Can I get your help to merge this PR into the blockchain commons repo? It has too many conflicts to easily merge.) I'd be glad to add give you maintainer privs. Thanks!

We are working now on some cli apps (companions to https://github.com/blockchainCommons/bc-seedtool-cli) which will be doing bitcoin Schnorr public keys and signatures.

**Comment by jonasnick** [comment]
If I understand the README correctly, this repo libsecp with (an older version of) the schnorrsig PR. Why not just set the repo master to the schnorrsig PR? What does the repo provide over the schnorrsig PR in libsecp?

**Comment by ChristopherA** [comment]
For some reason I can’t seem to merge this PR into master as I was able to before. And I don’t want to delete the repo and start over.

**Comment by ChristopherA** [comment]
The merge errors are:
```
Conflicting files
.travis.yml
configure.ac
include/secp256k1_schnorrsig.h
src/bench_schnorrsig.c
src/modules/schnorrsig/main_impl.h
src/modules/schnorrsig/tests_impl.h
src/scalar.h
src/scalar_4x64_impl.h
src/scalar_8x32_impl.h
src/scalar_low_impl.h
src/tests.C

```

**Comment by jonasnick** [comment]
Since you seem to confirm that this repo is libsecp with an older version of the schnorrsig PR I think you can resolve the conflicts always by taking the hunk from this PR.

**Comment by jonasnick** [comment]
By the way, why not update the schnorrsig implementation in secp-zkp and thereby join our efforts?

**Pull request merged**
